name: Update Productive Time

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *" # 매일 자정 실행 (UTC 기준)

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub Personal Access Token
          GIST_ID: ${{ secrets.GIST_ID }}   # Gist ID
          TIMEZONE: Asia/Seoul              # 한국 시간대
